import Head from "next/head.js";
// TODO: add import statement here for 'getPhoneData' and 'getAllPhoneIds' fns
import { getPhoneData, getAllPhoneIds } from "../../libs/phones";

type PhoneData = { id: number; model: string; price: number };
type ParamData = { params: { id: number } };

export async function getStaticProps({ params }: ParamData) {
  // TODO: Instead of this, fetch the matching record from the json data
  const phoneData = getPhoneData(params.id);
  //   const strData = JSON.stringify(phoneData);
  return {
    props: { phoneData },
  };
}

export async function getStaticPaths() {
  // TODO: This should fetch all the post ids from the JSON data
  const paths = getAllPhoneIds();
  //   console.log(paths);
  return {
    paths,
    fallback: false,
  };
}

// TODO: Not sure set props properly...
export default function Phone(phoneData: PhoneData) {
  const phone = phoneData;
  console.log("phoneData", phoneData);
  console.log("type of", typeof phoneData);
  console.log("phoneData.model", phoneData.model);
  return (
    <>
      <Head>
        <title>Buy an XX phone from Next Phones</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2>{phone.model}</h2>
      </main>
    </>
    //Insert page header from index (create a component for it)
    //Show the phone model and the price
  );
}
